// <auto-generated />
using System;
using LiquidCode.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiquidCode.Migrations
{
    [DbContext(typeof(LiquidDbContext))]
    [Migration("20251104135920_MergeContestWindows")]
    partial class MergeContestWindows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_articles_author_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_articles_is_deleted");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ArticleId", "TagId")
                        .HasName("pk_article_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_article_tags_tag_id");

                    b.ToTable("article_tags", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowEarlyFinish")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_early_finish");

                    b.Property<int?>("AttemptDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_duration_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_type");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_contests");

                    b.HasIndex("EndsAt")
                        .HasDatabaseName("ix_contests_ends_at");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_contests_group_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_contests_is_deleted");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_contests_starts_at");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_contests_visibility");

                    b.ToTable("contests", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestArticle", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContestId", "ArticleId")
                        .HasName("pk_contest_articles");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_contest_articles_article_id");

                    b.ToTable("contest_articles", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptIndex")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_index");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int?>("FinishedBy")
                        .HasColumnType("integer")
                        .HasColumnName("finished_by");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer")
                        .HasColumnName("solved_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_contest_attempts");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_contest_attempts_expires_at");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_contest_attempts_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contest_attempts_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contest_attempts_user_id");

                    b.HasIndex("ContestId", "UserId", "AttemptIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_contest_attempts_contest_id_user_id_attempt_index");

                    b.ToTable("contest_attempts", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestAttemptMissionResult", b =>
                {
                    b.Property<int>("ContestAttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_attempt_id");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer")
                        .HasColumnName("mission_id");

                    b.Property<int?>("BestSubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("best_submission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FirstAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_accepted_at");

                    b.Property<decimal>("HighestScore")
                        .HasColumnType("numeric")
                        .HasColumnName("highest_score");

                    b.Property<DateTime?>("LastSubmissionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submission_at");

                    b.Property<double>("Penalty")
                        .HasColumnType("double precision")
                        .HasColumnName("penalty");

                    b.Property<DateTime?>("SolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solved_at");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("integer")
                        .HasColumnName("submission_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContestAttemptId", "MissionId")
                        .HasName("pk_contest_attempt_mission_results");

                    b.HasIndex("BestSubmissionId")
                        .HasDatabaseName("ix_contest_attempt_mission_results_best_submission_id");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("ix_contest_attempt_mission_results_mission_id");

                    b.ToTable("contest_attempt_mission_results", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestMembership", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("ActiveAttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("active_attempt_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("integer")
                        .HasColumnName("invitation_id");

                    b.Property<bool>("IsAutoJoined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_joined");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastAttemptStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_started_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContestId", "UserId")
                        .HasName("pk_contest_memberships");

                    b.HasIndex("ActiveAttemptId")
                        .HasDatabaseName("ix_contest_memberships_active_attempt_id");

                    b.HasIndex("InvitationId")
                        .HasDatabaseName("ix_contest_memberships_invitation_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_contest_memberships_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contest_memberships_user_id");

                    b.ToTable("contest_memberships", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestMission", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer")
                        .HasColumnName("mission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContestId", "MissionId")
                        .HasName("pk_contest_missions");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("ix_contest_missions_mission_id");

                    b.ToTable("contest_missions", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_groups_is_deleted");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroupInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declined_at");

                    b.Property<int>("DeliveryChannel")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_channel");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("InviteeId")
                        .HasColumnType("integer")
                        .HasColumnName("invitee_id");

                    b.Property<int>("InviterId")
                        .HasColumnType("integer")
                        .HasColumnName("inviter_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_group_invitations");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_group_invitations_expires_at");

                    b.HasIndex("InviteeId")
                        .HasDatabaseName("ix_group_invitations_invitee_id");

                    b.HasIndex("InviterId")
                        .HasDatabaseName("ix_group_invitations_inviter_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_group_invitations_token");

                    b.HasIndex("GroupId", "InviteeId", "Status")
                        .HasDatabaseName("ix_group_invitations_group_id_invitee_id_status");

                    b.ToTable("group_invitations", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroupJoinToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_group_join_tokens");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_group_join_tokens_created_by_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_group_join_tokens_expires_at");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_join_tokens_group_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_group_join_tokens_token");

                    b.ToTable("group_join_tokens", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroupMembership", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("integer")
                        .HasColumnName("invitation_id");

                    b.Property<int?>("InvitedById")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_id");

                    b.Property<bool>("IsAutoJoined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_joined");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_memberships");

                    b.HasIndex("InvitationId")
                        .HasDatabaseName("ix_group_memberships_invitation_id");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("ix_group_memberships_invited_by_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_group_memberships_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_memberships_user_id");

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("s3key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_missions");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_missions_author_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_missions_created_at");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_missions_difficulty");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_missions_is_deleted");

                    b.ToTable("missions", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer")
                        .HasColumnName("mission_id");

                    b.Property<string>("StatementTexts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StatementTextsJson");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mission_statements");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_mission_statements_language");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("ix_mission_statements_mission_id");

                    b.HasIndex("MissionId", "Language", "Format")
                        .IsUnique()
                        .HasDatabaseName("ix_mission_statements_mission_id_language_format");

                    b.ToTable("mission_statements", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionStatementMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<string>("MediaKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("media_key");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("media_url");

                    b.Property<int>("StatementId")
                        .HasColumnType("integer")
                        .HasColumnName("statement_id");

                    b.HasKey("Id")
                        .HasName("pk_mission_statement_medias");

                    b.HasIndex("MediaKey")
                        .HasDatabaseName("ix_mission_statement_medias_media_key");

                    b.HasIndex("StatementId")
                        .HasDatabaseName("ix_mission_statement_medias_statement_id");

                    b.ToTable("mission_statement_medias", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionTag", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("integer")
                        .HasColumnName("mission_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MissionId", "TagId")
                        .HasName("pk_mission_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_mission_tags_tag_id");

                    b.ToTable("mission_tags", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbRefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DbUserId")
                        .HasColumnType("integer")
                        .HasColumnName("db_user_id");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_address");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("os_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Token")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("DbUserId")
                        .HasDatabaseName("ix_refresh_tokens_db_user_id");

                    b.HasIndex("Expires")
                        .HasDatabaseName("ix_refresh_tokens_expires");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfTests")
                        .HasColumnType("integer")
                        .HasColumnName("amount_of_tests");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentTest")
                        .HasColumnType("integer")
                        .HasColumnName("current_test");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("LanguageVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language_version");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer")
                        .HasColumnName("mission_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("source_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("status");

                    b.Property<int>("TestingErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("testing_error_code");

                    b.Property<string>("TestingMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("testing_message");

                    b.Property<int>("TestingState")
                        .HasColumnType("integer")
                        .HasColumnName("testing_state");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_solutions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_solutions_created_at");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("ix_solutions_mission_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_solutions_status");

                    b.ToTable("solutions", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_tags_is_deleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pass_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("salt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbUserSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContestAttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_attempt_id");

                    b.Property<int?>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("SolutionId")
                        .HasColumnType("integer")
                        .HasColumnName("solution_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_submits");

                    b.HasIndex("ContestAttemptId")
                        .HasDatabaseName("ix_user_submits_contest_attempt_id");

                    b.HasIndex("ContestId")
                        .HasDatabaseName("ix_user_submits_contest_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_submits_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_user_submits_is_deleted");

                    b.HasIndex("SolutionId")
                        .HasDatabaseName("ix_user_submits_solution_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_submits_user_id");

                    b.ToTable("user_submits", (string)null);
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbArticle", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articles_users_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbArticleTag", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbArticle", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_tags_articles_article_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbTag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_tags_tags_tag_id");

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContest", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbGroup", "Group")
                        .WithMany("Contests")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_contests_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestArticle", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbArticle", "Article")
                        .WithMany("ContestEntries")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_articles_articles_article_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContest", "Contest")
                        .WithMany("Articles")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_articles_contests_contest_id");

                    b.Navigation("Article");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestAttempt", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_attempts_contests_contest_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_attempts_users_user_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContestMembership", "Membership")
                        .WithMany("Attempts")
                        .HasForeignKey("ContestId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_attempts_contest_memberships_contest_id_user_id");

                    b.Navigation("Contest");

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestAttemptMissionResult", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUserSubmission", "BestSubmission")
                        .WithMany()
                        .HasForeignKey("BestSubmissionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contest_attempt_mission_results_user_submits_best_submissio");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContestAttempt", "ContestAttempt")
                        .WithMany("MissionResults")
                        .HasForeignKey("ContestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_attempt_mission_results_contest_attempts_contest_at");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbMission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_attempt_mission_results_missions_mission_id");

                    b.Navigation("BestSubmission");

                    b.Navigation("ContestAttempt");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestMembership", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContestAttempt", "ActiveAttempt")
                        .WithMany()
                        .HasForeignKey("ActiveAttemptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contest_memberships_contest_attempts_active_attempt_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContest", "Contest")
                        .WithMany("Memberships")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_memberships_contests_contest_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbGroupInvitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .HasConstraintName("fk_contest_memberships_group_invitations_invitation_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_memberships_users_user_id");

                    b.Navigation("ActiveAttempt");

                    b.Navigation("Contest");

                    b.Navigation("Invitation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestMission", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContest", "Contest")
                        .WithMany("Missions")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_missions_contests_contest_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbMission", "Mission")
                        .WithMany("ContestEntries")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_missions_missions_mission_id");

                    b.Navigation("Contest");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroupInvitation", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbGroup", "Group")
                        .WithMany("Invitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_invitations_groups_group_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "Invitee")
                        .WithMany()
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_invitations_users_invitee_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_invitations_users_inviter_id");

                    b.Navigation("Group");

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroupJoinToken", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_join_tokens_users_created_by_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbGroup", "Group")
                        .WithMany("JoinTokens")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_join_tokens_groups_group_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroupMembership", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_groups_group_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbGroupInvitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_memberships_group_invitations_invitation_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_memberships_users_invited_by_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("Invitation");

                    b.Navigation("InvitedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMission", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_missions_users_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionStatement", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbMission", "Mission")
                        .WithMany("Statements")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_statements_missions_mission_id");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionStatementMedia", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbMissionStatement", "Statement")
                        .WithMany("MediaFiles")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_statement_medias_mission_statements_statement_id");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionTag", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbMission", "Mission")
                        .WithMany("MissionTags")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_tags_missions_mission_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbTag", "Tag")
                        .WithMany("MissionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_tags_tags_tag_id");

                    b.Navigation("Mission");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbRefreshToken", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "DbUser")
                        .WithMany()
                        .HasForeignKey("DbUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_db_user_id");

                    b.Navigation("DbUser");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbSolution", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbMission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solutions_missions_mission_id");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbUserSubmission", b =>
                {
                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContestAttempt", "ContestAttempt")
                        .WithMany("Submissions")
                        .HasForeignKey("ContestAttemptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_submits_contest_attempts_contest_attempt_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbContest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .HasConstraintName("fk_user_submits_contests_contest_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbSolution", "Solution")
                        .WithMany()
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_submits_solutions_solution_id");

                    b.HasOne("LiquidCode.Infrastructure.Database.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_submits_users_user_id");

                    b.Navigation("Contest");

                    b.Navigation("ContestAttempt");

                    b.Navigation("Solution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbArticle", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("ContestEntries");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContest", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Memberships");

                    b.Navigation("Missions");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestAttempt", b =>
                {
                    b.Navigation("MissionResults");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbContestMembership", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbGroup", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Invitations");

                    b.Navigation("JoinTokens");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMission", b =>
                {
                    b.Navigation("ContestEntries");

                    b.Navigation("MissionTags");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbMissionStatement", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("LiquidCode.Infrastructure.Database.Entities.DbTag", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("MissionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
